# Generated by Django 5.1.6 on 2025-02-17 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('autor', models.CharField(max_length=100)),
                ('ano_de_leitura', models.IntegerField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
